
package pe.joedayz.libreria.servicios;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ListaLibrosService", targetNamespace = "http://servicios.libreria.joedayz.pe/", wsdlLocation = "http://localhost:8080/libros?wsdl")
public class ListaLibrosService
    extends Service
{

    private final static URL LISTALIBROSSERVICE_WSDL_LOCATION;
    private final static WebServiceException LISTALIBROSSERVICE_EXCEPTION;
    private final static QName LISTALIBROSSERVICE_QNAME = new QName("http://servicios.libreria.joedayz.pe/", "ListaLibrosService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/libros?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LISTALIBROSSERVICE_WSDL_LOCATION = url;
        LISTALIBROSSERVICE_EXCEPTION = e;
    }

    public ListaLibrosService() {
        super(__getWsdlLocation(), LISTALIBROSSERVICE_QNAME);
    }

    public ListaLibrosService(WebServiceFeature... features) {
        super(__getWsdlLocation(), LISTALIBROSSERVICE_QNAME, features);
    }

    public ListaLibrosService(URL wsdlLocation) {
        super(wsdlLocation, LISTALIBROSSERVICE_QNAME);
    }

    public ListaLibrosService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LISTALIBROSSERVICE_QNAME, features);
    }

    public ListaLibrosService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ListaLibrosService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ListaLibros
     */
    @WebEndpoint(name = "ListaLibrosPort")
    public ListaLibros getListaLibrosPort() {
        return super.getPort(new QName("http://servicios.libreria.joedayz.pe/", "ListaLibrosPort"), ListaLibros.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ListaLibros
     */
    @WebEndpoint(name = "ListaLibrosPort")
    public ListaLibros getListaLibrosPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://servicios.libreria.joedayz.pe/", "ListaLibrosPort"), ListaLibros.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LISTALIBROSSERVICE_EXCEPTION!= null) {
            throw LISTALIBROSSERVICE_EXCEPTION;
        }
        return LISTALIBROSSERVICE_WSDL_LOCATION;
    }

}
