
package pe.joedayz.libreria.servicios;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ListaLibros", targetNamespace = "http://servicios.libreria.joedayz.pe/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ListaLibros {


    /**
     * 
     * @return
     *     returns java.util.List<pe.joedayz.libreria.servicios.Libro>
     */
    @WebMethod
    @WebResult(name = "libro", targetNamespace = "")
    @RequestWrapper(localName = "listarLibros", targetNamespace = "http://servicios.libreria.joedayz.pe/", className = "pe.joedayz.libreria.servicios.ListarLibros")
    @ResponseWrapper(localName = "listarLibrosResponse", targetNamespace = "http://servicios.libreria.joedayz.pe/", className = "pe.joedayz.libreria.servicios.ListarLibrosResponse")
    @Action(input = "http://servicios.libreria.joedayz.pe/ListaLibros/listarLibrosRequest", output = "http://servicios.libreria.joedayz.pe/ListaLibros/listarLibrosResponse")
    public List<Libro> listarLibros();

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<pe.joedayz.libreria.servicios.Libro>
     */
    @WebMethod
    @WebResult(name = "libro", targetNamespace = "")
    @RequestWrapper(localName = "listarLibrosPaginacion", targetNamespace = "http://servicios.libreria.joedayz.pe/", className = "pe.joedayz.libreria.servicios.ListarLibrosPaginacion")
    @ResponseWrapper(localName = "listarLibrosPaginacionResponse", targetNamespace = "http://servicios.libreria.joedayz.pe/", className = "pe.joedayz.libreria.servicios.ListarLibrosPaginacionResponse")
    @Action(input = "http://servicios.libreria.joedayz.pe/ListaLibros/listarLibrosPaginacionRequest", output = "http://servicios.libreria.joedayz.pe/ListaLibros/listarLibrosPaginacionResponse")
    public List<Libro> listarLibrosPaginacion(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

}
